[package]
name = "uniqtoo"
version = "0.3.0"
authors = ["Jake Wharton <uniqtoo@jakewharton.com>"]
edition = "2018"
license = "Apache-2.0"
description = "A version of `sort | uniq -c` with output that updates in real-time as each line is parsed"
readme = "README.md"
repository = "https://github.com/JakeWharton/uniqtoo/"
categories = ["command-line-utilities"]
exclude = [".github/**"]

[dependencies]
clap = { version = "4.5.51", features = ["derive"] }

[profile.release]
lto = true
codegen-units = 1
