name: build and publish

on:
  push:
    branches:
      - trunk
    tags:
      - '*'

jobs:
  rustfmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          profile: minimal
          components: rustfmt

      - uses: actions-rs/cargo@v1
        name: cargo fmt
        with:
          command: fmt
          args: -- --check

  debug_build_and_checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: clippy

      - uses: actions-rs/cargo@v1
        name: cargo build
        with:
          command: build

      - uses: actions-rs/cargo@v1
        name: cargo test
        with:
          command: test

      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  release_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - uses: actions-rs/cargo@v1
        name: cargo build
        with:
          command: build
          args: --release

      - uses: actions-rs/cargo@v1
        name: cargo publish --dry-run
        with:
          command: publish
          args: --dry-run

  publish:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    needs:
      - rustfmt
      - debug_build_and_checks
      - release_build

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - uses: actions-rs/cargo@v1
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        with:
          command: publish

      - uses: ffurrer2/extract-release-notes@v1
        id: release_notes

      - uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.release_notes.outputs.release_notes }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
